   hostNODE_NAME:
       container_name: hostNODE_NAME 
       image: parity/parity:stable
       user: root
       working_dir: /home/parity'
       volumes:
       - ./deployment/chain/spec.json:/home/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
       - ./deployment/NODE_NAME/password:/home/parity/password:ro
       - ./deployment/NODE_NAME/authority.toml:/home/parity/authority.toml:ro
       - ./deployment/NODE_NAME/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
       - ./config/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
       - ./deployment/NODE_NAME/key.priv:/home/parity/data/network/key
       - ./data/NODE_NAME:/home/parity/data
       command: --chain /home/parity/spec.json --config /home/parity/authority.toml -d /home/parity/data
