   client:
       container_name: client
       image: parity/parity:stable
       user: root
       entrypoint: '/home/parity/bin/parity'
       working_dir: /home/parity'
       ports:
       - 8080:8080
       - 8180:8180
       - 8545:8545
       - 8546:8546
       - 30303:30303
       volumes:
       - ./deployment/chain/spec.json:/home/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
       - ./deployment/client/password:/home/parity/password:ro
       - ./deployment/client/client.toml:/home/parity/client.toml:ro
       - ./deployment/client/${NETWORK_NAME}:/home/parity/data/keys/${NETWORK_NAME}
       - ./config/dev.json:/home/parity/data/keys/${NETWORK_NAME}/dev.json
       - ./deployment/NODE_NAME/key.priv:/home/parity/data/network/key
       - ./data/client:/home/parity/data
       command: --chain /home/parity/spec.json --config /home/parity/client.toml -d /home/parity/data
