version: '2.0'
services:
   host1:
       container_name: host1
       image: parity/parity:stable
       user: root
       entrypoint: '/home/parity/bin/parity'
       working_dir: /home/parity'

       volumes:
       - ./deployment/chain/spec.json:/home/parity/spec.json:ro
       - ./deployment/chain/reserved_peers:/home/parity/reserved_peers:ro
       - ./deployment/chain/authcodes:/home/parity/data/authcodes
       - ./deployment/is_authority/password:/home/parity/password:ro
       - ./deployment/is_authority/authority.toml:/home/parity/authority.toml:ro
       - ./deployment/is_authority/${NETWORK_NAME}:/home/parity/data/keys/DevelopmentChain
       - ./data/is_authority:/home/parity/data
       command: --chain dev --config /home/parity/authority.toml -d /home/parity/data
